name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'master'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --base-href "/chatapiweb/"
      # - run: flutter build web --release
      - run: |
          cd ./build/web
          git init
          git config --global user.email 5712labs@gmail.com
          git config --global user.name 5712labd
          git status
          git remote add origin https://github.com/5712labs/chatapiweb.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin gh-pages -f
          
          